name: Build and Push Docker Image for nginx-utils container
on:
  push:
    branches:
      - mrajagopal-utils-pod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # Step 2: Debug: Verify api_stats.sh and repository content
      - name: List repository files
        run: ls -R .; pwd
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: nginx-utils/Dockerfile
          push: true
          tags: ghcr.io/nginx/nginx-utils:latest

  # Step 5: Install Trivy for Vulnerability Scanning
      - name: Install Trivy
        uses: aquasecurity/trivy-action
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/nginx-utils:latest
          format: json
          output: vuln-report.json

      - name: Upload Vulnerability Report
        uses: actions/upload-artifact
        with:
          name: vuln-report
          path: vuln-report.json
