name: Build and Push Docker Image for nginx-utils container
permissions:
  contents: read
  packages: write
  actions: write
on:
  release:
    types: [created]

env:
  RELEASE_VERSION: ${{ github.event.release.tag_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

        # Step 2: Debug: Verify api_stats.sh and repository content
      - name: List repository files
        run: ls -R .; pwd
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: nginx-utils/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/nginx/nginx-utils:${{ env.RELEASE_VERSION }}
            ghcr.io/nginx/nginx-utils:latest


  # Step 5: Install Trivy for Vulnerability Scanning
      - name: Install Trivy and scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.31.0

        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/nginx-utils:latest
          format: json
          output: vuln-report.json

      - name: Upload Vulnerability Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: vuln-report
          path: vuln-report.json
