name: Build and upload release artifact

permissions:
  contents: read

on:
  release:
    types: [created]

env:
  RELEASE_VERSION: ${{ github.event.release.tag_name }}

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Release Version
      run: echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.4'

    - name: Build
      run: |
        BUILD=$(git log --format='%H' -n 1)
        VERSION=$RELEASE_VERSION
        OSES="linux darwin windows"
        ARCHS="amd64 arm64"
        IFS=" "

        for OS in $OSES; do
        for ARCH in $ARCHS; do
        echo "OS: ${OS} and ARCH: ${ARCH}"
        CGO_ENABLED=0 GOOS=${OS} GOARCH=${ARCH} go build -ldflags "-w -s -X github.com/nginxinc/nginx-k8s-supportpkg/pkg/version.Build=$BUILD\
                                                   -X github.com/nginxinc/nginx-k8s-supportpkg/pkg/version.Version=$VERSION"\
                                                   -o release/kubectl-nginx_supportpkg_${VERSION}_${OS}_${ARCH}/kubectl-nginx_supportpkg
        cp LICENSE release/kubectl-nginx_supportpkg_${VERSION}_${OS}_${ARCH}/
        tar czvf release/kubectl-nginx_supportpkg_${VERSION}_${OS}_${ARCH}.tar.gz -C release/kubectl-nginx_supportpkg_${VERSION}_${OS}_${ARCH}/ .
        done; done

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./release/*.gz"]'

    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.46